apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sparkyfish-server.fullname" . }}
  labels:
    {{- include "sparkyfish-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sparkyfish-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sparkyfish-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          args:
            - -listen-addr=:7121
            {{- if .Values.sparkyfish.cname }}
            - -cname={{ .Values.sparkyfish.cname }}
            {{- end }}
            {{- if .Values.sparkyfish.location }}
            - -location={{ .Values.sparkyfish.location }}
            {{- end }}
            {{- if .Values.sparkyfish.debug }}
            - -debug
            {{- end }}
          ports:
            - name: sparkyfish
              containerPort: 7121
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
